/**
 * Auto-generated by generate_creds.js
 * Static list of users and passwords for seeding.
 */
module.exports = [
  {
    "role": "admin",
    "email": "admin@CU.in",
    "firstName": "Admin",
    "lastName": "User",
    "password": "eFtWmp8m"
  },
  {
    "role": "teacher",
    "email": "testteacher@CU.in",
    "firstName": "Test",
    "lastName": "Teacher",
    "password": "5EgrKplI"
  },
  {
    "role": "editor",
    "email": "editor1@CU.in",
    "firstName": "Editor",
    "lastName": "One",
    "password": "Ktg0cO3s"
  },
  {
    "role": "editor",
    "email": "editor2@CU.in",
    "firstName": "Editor",
    "lastName": "Two",
    "password": "zVoksvDt"
  },
  {
    "role": "teaching assistant",
    "email": "ta1@CU.in",
    "firstName": "TA",
    "lastName": "One",
    "password": "ETiQsyNL"
  },
  {
    "role": "teaching assistant",
    "email": "ta2@CU.in",
    "firstName": "TA",
    "lastName": "Two",
    "password": "7IzxN98u"
  },
  {
    "role": "publisher",
    "email": "publisher1@CU.in",
    "firstName": "Publisher",
    "lastName": "One",
    "password": "TeCUmx4v"
  },
  {
    "role": "publisher",
    "email": "publisher2@CU.in",
    "firstName": "Publisher",
    "lastName": "Two",
    "password": "dAr1XgxM"
  },
  {
    "role": "teacher",
    "email": "maria.fulgen@clg.edu",
    "firstName": "Maria",
    "lastName": "Fulgen",
    "isLegacy": true,
    "password": "nwNKUr9r"
  },
  {
    "role": "teacher",
    "email": "pooja.jain@clg.edu",
    "firstName": "Pooja",
    "lastName": "Jain",
    "isLegacy": true,
    "password": "fvLCWWBs"
  },
  {
    "role": "teacher",
    "email": "sudhanshu.n@clg.edu",
    "firstName": "Sudhanshu",
    "lastName": "N",
    "isLegacy": true,
    "password": "t5oy23Wx"
  },
  {
    "role": "teacher",
    "email": "lakshmi.b@clg.edu",
    "firstName": "Lakshmi",
    "lastName": "B",
    "isLegacy": true,
    "password": "MBKIs1cN"
  },
  {
    "role": "teacher",
    "email": "shaeril.michael.almeida@christuniversity.in",
    "firstName": "Shaeril",
    "lastName": "Almeida",
    "isLegacy": true,
    "password": "KCtMoZWP"
  },
  {
    "role": "teacher",
    "email": "Jagadesh.chander@christuniversity.in",
    "firstName": "Jagadeesh",
    "lastName": "",
    "isLegacy": true,
    "password": "MmfY3Hpk"
  },
  {
    "role": "teacher",
    "email": "geetanjali.purswani@clg.edu",
    "firstName": "Geetanjali",
    "lastName": "Purswani",
    "isLegacy": true,
    "password": "cpwwACsc"
  },
  {
    "role": "teacher",
    "email": "jinny.john@christuniversity.in",
    "firstName": "Jinny",
    "lastName": "John",
    "isLegacy": true,
    "password": "CvBQPzh2"
  },
  {
    "role": "teacher",
    "email": "james.joseph@christuniversity.in",
    "firstName": "James",
    "lastName": "Joseph",
    "isLegacy": true,
    "password": "W4iOCnMu"
  },
  {
    "role": "teacher",
    "email": "vaidhehi.v@christuniversity.in",
    "firstName": "Vaidhehi",
    "lastName": "V",
    "isLegacy": true,
    "password": "zQRFFl8f"
  },
  {
    "role": "teacher",
    "email": "binayak.dutta@christuniversity.in",
    "firstName": "Binayak",
    "lastName": "Dutta",
    "isLegacy": true,
    "password": "5GSKxY5r"
  },
  {
    "role": "teacher",
    "email": "suresh.kalaimani@christuniversity.in",
    "firstName": "Suresh",
    "lastName": "Kalaimani",
    "isLegacy": true,
    "password": "KnDzKQGN"
  },
  {
    "role": "teacher",
    "email": "cynthia.t@christuniversity.in",
    "firstName": "Cynthia",
    "lastName": "T",
    "isLegacy": true,
    "password": "t0Cz8kKy"
  },
  {
    "role": "teacher",
    "email": "nizar.banu@christuniversity.in",
    "firstName": "Nizar",
    "lastName": "Banu",
    "isLegacy": true,
    "password": "6ojMGKWB"
  },
  {
    "role": "teacher",
    "email": "nisha.varghese@christuniversity.in",
    "firstName": "Nisha",
    "lastName": "Varghese",
    "isLegacy": true,
    "password": "gxii7Dvi"
  },
  {
    "role": "teacher",
    "email": "manasa.kulkarni@christuniversity.in",
    "firstName": "Manasa",
    "lastName": "Kulkarni",
    "isLegacy": true,
    "password": "XgKMwaop"
  },
  {
    "role": "teacher",
    "email": "thirunavukkarasu.v@christuniversity.in",
    "firstName": "Thirunavukkarasu",
    "lastName": "V",
    "isLegacy": true,
    "password": "UjIhhMzt"
  },
  {
    "role": "teacher",
    "email": "rohini.v@christuniversity.in",
    "firstName": "Rohini",
    "lastName": "V",
    "isLegacy": true,
    "password": "Qj8czYjO"
  },
  {
    "role": "teacher",
    "email": "deepa.v.jose@christuniversity.in",
    "firstName": "Deepa",
    "lastName": "V Jose",
    "isLegacy": true,
    "password": "7O3LE69E"
  },
  {
    "role": "teacher",
    "email": "sandeep.j@christuniversity.in",
    "firstName": "Sandeep",
    "lastName": "J",
    "isLegacy": true,
    "password": "3NAkeUSc"
  },
  {
    "role": "teacher",
    "email": "puneeth.v@christuniversity.in",
    "firstName": "Puneeth",
    "lastName": "V",
    "isLegacy": true,
    "password": "svaWZHwe"
  },
  {
    "role": "teacher",
    "email": "sangeetha.g@christuniversity.in",
    "firstName": "Sangeetha",
    "lastName": "G",
    "isLegacy": true,
    "password": "LvBTt2Vn"
  },
  {
    "role": "teacher",
    "email": "beaulah.s@christuniversity.in",
    "firstName": "Beaulah",
    "lastName": "S",
    "isLegacy": true,
    "password": "rr5ywTE5"
  },
  {
    "role": "teacher",
    "email": "sridevi.r@christuniversity.in",
    "firstName": "Sridevi",
    "lastName": "R",
    "isLegacy": true,
    "password": "TnuDuCHK"
  },
  {
    "role": "teacher",
    "email": "nismon.rio@christuniversity.in",
    "firstName": "Nismon",
    "lastName": "Rio",
    "isLegacy": true,
    "password": "KIJ1xZJh"
  },
  {
    "role": "teacher",
    "email": "laxmi.basappa@christuniversity.in",
    "firstName": "Laxmi",
    "lastName": "Basappa",
    "isLegacy": true,
    "password": "3ufWE0R8"
  },
  {
    "role": "teacher",
    "email": "manimekala.b@christuniversity.in",
    "firstName": "Manimekala",
    "lastName": "B",
    "isLegacy": true,
    "password": "gjwUfj6D"
  },
  {
    "role": "teacher",
    "email": "balakrishnan.c@christuniversity.in",
    "firstName": "Balakrishnan",
    "lastName": "C",
    "isLegacy": true,
    "password": "l16n7bAY"
  },
  {
    "role": "teacher",
    "email": "deepa.s@christuniversity.in",
    "firstName": "Deepa",
    "lastName": "S",
    "isLegacy": true,
    "password": "OumjqbDK"
  },
  {
    "role": "teacher",
    "email": "jayapriya.j@christuniversity.in",
    "firstName": "Jayapriya",
    "lastName": "J",
    "isLegacy": true,
    "password": "xAfXzvZe"
  },
  {
    "role": "teacher",
    "email": "umamaheswari.d@christuniversity.in",
    "firstName": "Umamaheswari",
    "lastName": "D",
    "isLegacy": true,
    "password": "IDH91aUa"
  },
  {
    "role": "teacher",
    "email": "arpita.teacher@clg.edu",
    "firstName": "Arpita",
    "lastName": "",
    "isLegacy": true,
    "password": "OZs06ani"
  },
  {
    "role": "teacher",
    "email": "anjali.pk@clg.edu",
    "firstName": "Anjali",
    "lastName": "PK",
    "isLegacy": true,
    "password": "PQqoFv9y"
  },
  {
    "role": "teacher",
    "email": "gerard.rassendren@clg.edu",
    "firstName": "Gerard",
    "lastName": "Rassendren",
    "isLegacy": true,
    "password": "buwmnSfN"
  },
  {
    "role": "teacher",
    "email": "sankar.varma@clg.edu",
    "firstName": "Sankar",
    "lastName": "Varma",
    "isLegacy": true,
    "password": "xM3Apl9o"
  },
  {
    "role": "teacher",
    "email": "aleena.teacher@clg.edu",
    "firstName": "Aleena",
    "lastName": "",
    "isLegacy": true,
    "password": "Drv57izn"
  }
];
