module.exports = {
    schools: [
        { id: 1, name: 'School of Management' },
        { id: 4, name: 'School of Science' },
        { id: 8, name: 'School of Social Sciences' },
    ],
    programs: [
        { id: 1, schoolId: 1, name: 'Bachelor of Commerce', code: 'BCOM' },
        { id: 4, schoolId: 4, name: 'Master of Science in Artificial Intelligence', code: 'MAI' },
        { id: 5, schoolId: 4, name: 'Master of Computer Applications', code: 'MCA' },
        { id: 6, schoolId: 4, name: 'Bachelor of Computer Applications', code: 'BCA' },
        { id: 7, schoolId: 4, name: 'Master of Science in Data Science', code: 'MDS' },
        { id: 8, schoolId: 8, name: 'Master of Arts in Economics', code: 'MAECO' },
    ],
    courses: [
        { id: 1, programId: 1, title: 'Banking Law & Operations - COM0101 - 2', code: 'COM0101 - 2' },
        { id: 2, programId: 1, title: 'Business Mathematics  Statistics', code: 'BCOM-002' },
        { id: 3, programId: 1, title: 'Communicative English - II', code: 'BCOM-003' },
        { id: 4, programId: 1, title: 'Corporate  Accounting - COMO201 - 2', code: 'COMO201 - 2' },
        { id: 5, programId: 1, title: 'Corporate Law & Administration - COMO102 - 2', code: 'COMO102 - 2' },
        { id: 6, programId: 1, title: 'Positive  Psychology', code: 'BCOM-006' },
        { id: 7, programId: 1, title: 'Spreadsheet for Business COMO161 - 2', code: 'COMO161 - 2' },
        { id: 22, programId: 4, title: 'Computational Mathematics - II', code: 'MAI-OL404-2' },
        { id: 23, programId: 4, title: 'Data Structures and Algorithm', code: 'MAI-OL405-2' },
        { id: 24, programId: 4, title: 'Deep Learining', code: 'MAI-OL424-2' },
        { id: 25, programId: 4, title: 'Java Programming', code: 'MAI-OL525-2' },
        { id: 26, programId: 4, title: 'Natural Language Processing', code: 'MAI-OL526-2' },
        { id: 27, programId: 5, title: 'Artificial Intelligence & Machine Learning', code: 'MCA-OL-501-2' },
        { id: 28, programId: 5, title: 'Data Communication & Computer Networks', code: 'MCA-OL-402-2' },
        { id: 29, programId: 5, title: 'Data Structures & Algorithms', code: 'MCA-OL-403-2' },
        { id: 30, programId: 5, title: 'Full Stack Development', code: 'MCA-OL-404-2' },
        { id: 31, programId: 5, title: 'Java Programming', code: 'MCA-OL-405-2' },
        { id: 32, programId: 6, title: 'Discrete mathematics', code: 'BCA-OL-105-2' },
        { id: 33, programId: 6, title: 'OPERATING SYSTEM', code: 'BCA-OL-106-2' },
        { id: 34, programId: 6, title: 'OBJECT ORIENTED PROGRAMMING USING C++', code: 'BCA-OL-107-2' },
        { id: 35, programId: 6, title: 'PRINCIPLES OF SOFTWARE DEVELOPMENT', code: 'BCA-OL-108-2' },
        { id: 36, programId: 6, title: 'FULL STACK DEVELOPMENT', code: 'BCA-OL-209-2' },
        { id: 37, programId: 7, title: 'Applied Regression Analysis', code: 'MDSO405-2' },
        { id: 38, programId: 7, title: 'Data Structures & Algorithms', code: 'MDSO503-3' },
        { id: 39, programId: 7, title: 'Data Visualization', code: 'MDSO461-2' },
        { id: 40, programId: 7, title: 'Database Technologies', code: 'MDSO404-2' },
        { id: 41, programId: 7, title: 'Machine Learning', code: 'MDSO502-2' },
        { id: 42, programId: 7, title: 'Machine Learning Lab', code: 'MDSO512-2' },
        { id: 43, programId: 8, title: 'Econometric Methods', code: 'ECO409-2' },
        { id: 44, programId: 8, title: 'Economics of Growth and Development', code: 'ECO406-2' },
        { id: 45, programId: 8, title: 'History of Economic Thought', code: 'ECO408-2' },
        { id: 46, programId: 8, title: 'International Trade and Finance', code: 'ECO410-2' },
        { id: 47, programId: 8, title: 'Public Finance and policy', code: 'ECO407-2' },
    ],
    users: [
        { id: 10, roleId: 2, email: 'maria.fulgen@clg.edu', firstName: 'Maria', lastName: 'Fulgen' },
        { id: 11, roleId: 2, email: 'pooja.jain@clg.edu', firstName: 'Pooja', lastName: 'Jain' },
        { id: 12, roleId: 2, email: 'sudhanshu.n@clg.edu', firstName: 'Sudhanshu', lastName: 'N' },
        { id: 13, roleId: 2, email: 'lakshmi.b@clg.edu', firstName: 'Lakshmi', lastName: 'B' },
        { id: 14, roleId: 2, email: 'shaeril.michael.almeida@christuniversity.in', firstName: 'Shaeril', lastName: 'Almeida' },
        { id: 15, roleId: 2, email: 'Jagadesh.chander@christuniversity.in', firstName: 'Jagadeesh', lastName: '' },
        { id: 16, roleId: 2, email: 'geetanjali.purswani@clg.edu', firstName: 'Geetanjali', lastName: 'Purswani' },
        { id: 25, roleId: 2, email: 'jinny.john@christuniversity.in', firstName: 'Jinny', lastName: 'John' },
        { id: 26, roleId: 2, email: 'james.joseph@christuniversity.in', firstName: 'James', lastName: 'Joseph' },
        { id: 27, roleId: 2, email: 'vaidhehi.v@christuniversity.in', firstName: 'Vaidhehi', lastName: 'V' },
        { id: 28, roleId: 2, email: 'binayak.dutta@christuniversity.in', firstName: 'Binayak', lastName: 'Dutta' },
        { id: 29, roleId: 2, email: 'suresh.kalaimani@christuniversity.in', firstName: 'Suresh', lastName: 'Kalaimani' },
        { id: 30, roleId: 2, email: 'cynthia.t@christuniversity.in', firstName: 'Cynthia', lastName: 'T' },
        { id: 31, roleId: 2, email: 'nizar.banu@christuniversity.in', firstName: 'Nizar', lastName: 'Banu' },
        { id: 32, roleId: 2, email: 'nisha.varghese@christuniversity.in', firstName: 'Nisha', lastName: 'Varghese' },
        { id: 33, roleId: 2, email: 'manasa.kulkarni@christuniversity.in', firstName: 'Manasa', lastName: 'Kulkarni' },
        { id: 34, roleId: 2, email: 'thirunavukkarasu.v@christuniversity.in', firstName: 'Thirunavukkarasu', lastName: 'V' },
        { id: 35, roleId: 2, email: 'rohini.v@christuniversity.in', firstName: 'Rohini', lastName: 'V' },
        { id: 36, roleId: 2, email: 'deepa.v.jose@christuniversity.in', firstName: 'Deepa', lastName: 'V Jose' },
        { id: 37, roleId: 2, email: 'sandeep.j@christuniversity.in', firstName: 'Sandeep', lastName: 'J' },
        { id: 43, roleId: 2, email: 'puneeth.v@christuniversity.in', firstName: 'Puneeth', lastName: 'V' },
        { id: 44, roleId: 2, email: 'sangeetha.g@christuniversity.in', firstName: 'Sangeetha', lastName: 'G' },
        { id: 45, roleId: 2, email: 'beaulah.s@christuniversity.in', firstName: 'Beaulah', lastName: 'S' },
        { id: 46, roleId: 2, email: 'sridevi.r@christuniversity.in', firstName: 'Sridevi', lastName: 'R' },
        { id: 47, roleId: 2, email: 'nismon.rio@christuniversity.in', firstName: 'Nismon', lastName: 'Rio' },
        { id: 48, roleId: 2, email: 'laxmi.basappa@christuniversity.in', firstName: 'Laxmi', lastName: 'Basappa' },
        { id: 49, roleId: 2, email: 'manimekala.b@christuniversity.in', firstName: 'Manimekala', lastName: 'B' },
        { id: 50, roleId: 2, email: 'balakrishnan.c@christuniversity.in', firstName: 'Balakrishnan', lastName: 'C' },
        { id: 51, roleId: 2, email: 'deepa.s@christuniversity.in', firstName: 'Deepa', lastName: 'S' },
        { id: 52, roleId: 2, email: 'jayapriya.j@christuniversity.in', firstName: 'Jayapriya', lastName: 'J' },
        { id: 53, roleId: 2, email: 'umamaheswari.d@christuniversity.in', firstName: 'Umamaheswari', lastName: 'D' },
        { id: 56, roleId: 2, email: 'arpita.teacher@clg.edu', firstName: 'Arpita', lastName: '' },
        { id: 57, roleId: 2, email: 'anjali.pk@clg.edu', firstName: 'Anjali', lastName: 'PK' },
        { id: 59, roleId: 2, email: 'gerard.rassendren@clg.edu', firstName: 'Gerard', lastName: 'Rassendren' },
        { id: 60, roleId: 2, email: 'sankar.varma@clg.edu', firstName: 'Sankar', lastName: 'Varma' },
        { id: 62, roleId: 2, email: 'aleena.teacher@clg.edu', firstName: 'Aleena', lastName: '' },
    ],
    // userId, courseId
    assignments: [
        { userId: 10, courseId: 1 },
        { userId: 11, courseId: 2 },
        { userId: 12, courseId: 3 },
        { userId: 13, courseId: 4 },
        { userId: 14, courseId: 5 },
        { userId: 15, courseId: 6 },
        { userId: 16, courseId: 7 },
        { userId: 25, courseId: 22 },
        { userId: 26, courseId: 22 },
        { userId: 27, courseId: 23 },
        { userId: 27, courseId: 29 },
        { userId: 28, courseId: 23 },
        { userId: 28, courseId: 29 },
        { userId: 29, courseId: 24 },
        { userId: 29, courseId: 30 },
        { userId: 30, courseId: 24 },
        { userId: 30, courseId: 30 },
        { userId: 30, courseId: 31 },
        { userId: 31, courseId: 25 },
        { userId: 32, courseId: 26 },
        { userId: 33, courseId: 26 },
        { userId: 34, courseId: 27 },
        { userId: 35, courseId: 27 },
        { userId: 36, courseId: 28 },
        { userId: 37, courseId: 28 },
        { userId: 43, courseId: 32 },
        { userId: 44, courseId: 33 },
        { userId: 45, courseId: 34 },
        { userId: 46, courseId: 35 },
        { userId: 47, courseId: 36 },
        { userId: 48, courseId: 37 },
        { userId: 49, courseId: 38 },
        { userId: 50, courseId: 40 },
        { userId: 51, courseId: 40 },
        { userId: 52, courseId: 41 },
        { userId: 52, courseId: 42 },
        { userId: 53, courseId: 41 },
        { userId: 53, courseId: 42 },
        { userId: 56, courseId: 43 },
        { userId: 56, courseId: 44 },
        { userId: 56, courseId: 46 },
        { userId: 57, courseId: 44 },
        { userId: 59, courseId: 45 },
        { userId: 60, courseId: 45 },
        { userId: 62, courseId: 47 },
    ]
};
